/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DAGTask represents a node in the graph during DAG execution
    /// </summary>
    [DataContract(Name = "io.argoproj.workflow.v1alpha1.DAGTask")]
    public partial class IoArgoprojWorkflowV1alpha1DAGTask : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IoArgoprojWorkflowV1alpha1DAGTask" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IoArgoprojWorkflowV1alpha1DAGTask() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IoArgoprojWorkflowV1alpha1DAGTask" /> class.
        /// </summary>
        /// <param name="arguments">arguments.</param>
        /// <param name="continueOn">continueOn.</param>
        /// <param name="dependencies">Dependencies are name of other targets which this depends on.</param>
        /// <param name="depends">Depends are name of other targets which this depends on.</param>
        /// <param name="hooks">Hooks hold the lifecycle hook which is invoked at lifecycle of task, irrespective of the success, failure, or error status of the primary task.</param>
        /// <param name="inline">inline.</param>
        /// <param name="name">Name is the name of the target (required).</param>
        /// <param name="onExit">OnExit is a template reference which is invoked at the end of the template, irrespective of the success, failure, or error of the primary template. DEPRECATED: Use Hooks[exit].Template instead..</param>
        /// <param name="template">Name of template to execute.</param>
        /// <param name="templateRef">templateRef.</param>
        /// <param name="when">When is an expression in which the task should conditionally execute.</param>
        /// <param name="withItems">WithItems expands a task into multiple parallel tasks from the items in the list.</param>
        /// <param name="withParam">WithParam expands a task into multiple parallel tasks from the value in the parameter, which is expected to be a JSON list..</param>
        /// <param name="withSequence">withSequence.</param>
        public IoArgoprojWorkflowV1alpha1DAGTask(IoArgoprojWorkflowV1alpha1Arguments arguments = default(IoArgoprojWorkflowV1alpha1Arguments), IoArgoprojWorkflowV1alpha1ContinueOn continueOn = default(IoArgoprojWorkflowV1alpha1ContinueOn), List<string> dependencies = default(List<string>), string depends = default(string), Dictionary<string, IoArgoprojWorkflowV1alpha1LifecycleHook> hooks = default(Dictionary<string, IoArgoprojWorkflowV1alpha1LifecycleHook>), IoArgoprojWorkflowV1alpha1Template inline = default(IoArgoprojWorkflowV1alpha1Template), string name = default(string), string onExit = default(string), string template = default(string), IoArgoprojWorkflowV1alpha1TemplateRef templateRef = default(IoArgoprojWorkflowV1alpha1TemplateRef), string when = default(string), List<Object> withItems = default(List<Object>), string withParam = default(string), IoArgoprojWorkflowV1alpha1Sequence withSequence = default(IoArgoprojWorkflowV1alpha1Sequence))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for IoArgoprojWorkflowV1alpha1DAGTask and cannot be null");
            }
            this.Name = name;
            this.Arguments = arguments;
            this.ContinueOn = continueOn;
            this.Dependencies = dependencies;
            this.Depends = depends;
            this.Hooks = hooks;
            this.Inline = inline;
            this.OnExit = onExit;
            this.Template = template;
            this.TemplateRef = templateRef;
            this.When = when;
            this.WithItems = withItems;
            this.WithParam = withParam;
            this.WithSequence = withSequence;
        }

        /// <summary>
        /// Gets or Sets Arguments
        /// </summary>
        [DataMember(Name = "arguments", EmitDefaultValue = false)]
        public IoArgoprojWorkflowV1alpha1Arguments Arguments { get; set; }

        /// <summary>
        /// Gets or Sets ContinueOn
        /// </summary>
        [DataMember(Name = "continueOn", EmitDefaultValue = false)]
        public IoArgoprojWorkflowV1alpha1ContinueOn ContinueOn { get; set; }

        /// <summary>
        /// Dependencies are name of other targets which this depends on
        /// </summary>
        /// <value>Dependencies are name of other targets which this depends on</value>
        [DataMember(Name = "dependencies", EmitDefaultValue = false)]
        public List<string> Dependencies { get; set; }

        /// <summary>
        /// Depends are name of other targets which this depends on
        /// </summary>
        /// <value>Depends are name of other targets which this depends on</value>
        [DataMember(Name = "depends", EmitDefaultValue = false)]
        public string Depends { get; set; }

        /// <summary>
        /// Hooks hold the lifecycle hook which is invoked at lifecycle of task, irrespective of the success, failure, or error status of the primary task
        /// </summary>
        /// <value>Hooks hold the lifecycle hook which is invoked at lifecycle of task, irrespective of the success, failure, or error status of the primary task</value>
        [DataMember(Name = "hooks", EmitDefaultValue = false)]
        public Dictionary<string, IoArgoprojWorkflowV1alpha1LifecycleHook> Hooks { get; set; }

        /// <summary>
        /// Gets or Sets Inline
        /// </summary>
        [DataMember(Name = "inline", EmitDefaultValue = false)]
        public IoArgoprojWorkflowV1alpha1Template Inline { get; set; }

        /// <summary>
        /// Name is the name of the target
        /// </summary>
        /// <value>Name is the name of the target</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// OnExit is a template reference which is invoked at the end of the template, irrespective of the success, failure, or error of the primary template. DEPRECATED: Use Hooks[exit].Template instead.
        /// </summary>
        /// <value>OnExit is a template reference which is invoked at the end of the template, irrespective of the success, failure, or error of the primary template. DEPRECATED: Use Hooks[exit].Template instead.</value>
        [DataMember(Name = "onExit", EmitDefaultValue = false)]
        public string OnExit { get; set; }

        /// <summary>
        /// Name of template to execute
        /// </summary>
        /// <value>Name of template to execute</value>
        [DataMember(Name = "template", EmitDefaultValue = false)]
        public string Template { get; set; }

        /// <summary>
        /// Gets or Sets TemplateRef
        /// </summary>
        [DataMember(Name = "templateRef", EmitDefaultValue = false)]
        public IoArgoprojWorkflowV1alpha1TemplateRef TemplateRef { get; set; }

        /// <summary>
        /// When is an expression in which the task should conditionally execute
        /// </summary>
        /// <value>When is an expression in which the task should conditionally execute</value>
        [DataMember(Name = "when", EmitDefaultValue = false)]
        public string When { get; set; }

        /// <summary>
        /// WithItems expands a task into multiple parallel tasks from the items in the list
        /// </summary>
        /// <value>WithItems expands a task into multiple parallel tasks from the items in the list</value>
        [DataMember(Name = "withItems", EmitDefaultValue = false)]
        public List<Object> WithItems { get; set; }

        /// <summary>
        /// WithParam expands a task into multiple parallel tasks from the value in the parameter, which is expected to be a JSON list.
        /// </summary>
        /// <value>WithParam expands a task into multiple parallel tasks from the value in the parameter, which is expected to be a JSON list.</value>
        [DataMember(Name = "withParam", EmitDefaultValue = false)]
        public string WithParam { get; set; }

        /// <summary>
        /// Gets or Sets WithSequence
        /// </summary>
        [DataMember(Name = "withSequence", EmitDefaultValue = false)]
        public IoArgoprojWorkflowV1alpha1Sequence WithSequence { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IoArgoprojWorkflowV1alpha1DAGTask {\n");
            sb.Append("  Arguments: ").Append(Arguments).Append("\n");
            sb.Append("  ContinueOn: ").Append(ContinueOn).Append("\n");
            sb.Append("  Dependencies: ").Append(Dependencies).Append("\n");
            sb.Append("  Depends: ").Append(Depends).Append("\n");
            sb.Append("  Hooks: ").Append(Hooks).Append("\n");
            sb.Append("  Inline: ").Append(Inline).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OnExit: ").Append(OnExit).Append("\n");
            sb.Append("  Template: ").Append(Template).Append("\n");
            sb.Append("  TemplateRef: ").Append(TemplateRef).Append("\n");
            sb.Append("  When: ").Append(When).Append("\n");
            sb.Append("  WithItems: ").Append(WithItems).Append("\n");
            sb.Append("  WithParam: ").Append(WithParam).Append("\n");
            sb.Append("  WithSequence: ").Append(WithSequence).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
