/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// IoArgoprojWorkflowV1alpha1LifecycleHook
    /// </summary>
    [DataContract(Name = "io.argoproj.workflow.v1alpha1.LifecycleHook")]
    public partial class IoArgoprojWorkflowV1alpha1LifecycleHook : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IoArgoprojWorkflowV1alpha1LifecycleHook" /> class.
        /// </summary>
        /// <param name="arguments">arguments.</param>
        /// <param name="expression">Expression is a condition expression for when a node will be retried. If it evaluates to false, the node will not be retried and the retry strategy will be ignored.</param>
        /// <param name="template">Template is the name of the template to execute by the hook.</param>
        /// <param name="templateRef">templateRef.</param>
        public IoArgoprojWorkflowV1alpha1LifecycleHook(IoArgoprojWorkflowV1alpha1Arguments arguments = default(IoArgoprojWorkflowV1alpha1Arguments), string expression = default(string), string template = default(string), IoArgoprojWorkflowV1alpha1TemplateRef templateRef = default(IoArgoprojWorkflowV1alpha1TemplateRef))
        {
            this.Arguments = arguments;
            this.Expression = expression;
            this.Template = template;
            this.TemplateRef = templateRef;
        }

        /// <summary>
        /// Gets or Sets Arguments
        /// </summary>
        [DataMember(Name = "arguments", EmitDefaultValue = false)]
        public IoArgoprojWorkflowV1alpha1Arguments Arguments { get; set; }

        /// <summary>
        /// Expression is a condition expression for when a node will be retried. If it evaluates to false, the node will not be retried and the retry strategy will be ignored
        /// </summary>
        /// <value>Expression is a condition expression for when a node will be retried. If it evaluates to false, the node will not be retried and the retry strategy will be ignored</value>
        [DataMember(Name = "expression", EmitDefaultValue = false)]
        public string Expression { get; set; }

        /// <summary>
        /// Template is the name of the template to execute by the hook
        /// </summary>
        /// <value>Template is the name of the template to execute by the hook</value>
        [DataMember(Name = "template", EmitDefaultValue = false)]
        public string Template { get; set; }

        /// <summary>
        /// Gets or Sets TemplateRef
        /// </summary>
        [DataMember(Name = "templateRef", EmitDefaultValue = false)]
        public IoArgoprojWorkflowV1alpha1TemplateRef TemplateRef { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IoArgoprojWorkflowV1alpha1LifecycleHook {\n");
            sb.Append("  Arguments: ").Append(Arguments).Append("\n");
            sb.Append("  Expression: ").Append(Expression).Append("\n");
            sb.Append("  Template: ").Append(Template).Append("\n");
            sb.Append("  TemplateRef: ").Append(TemplateRef).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
