/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// WorkflowLevelArtifactGC describes how to delete artifacts from completed Workflows - this spec is used on the Workflow level
    /// </summary>
    [DataContract(Name = "io.argoproj.workflow.v1alpha1.WorkflowLevelArtifactGC")]
    public partial class IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC" /> class.
        /// </summary>
        /// <param name="forceFinalizerRemoval">ForceFinalizerRemoval: if set to true, the finalizer will be removed in the case that Artifact GC fails.</param>
        /// <param name="podMetadata">podMetadata.</param>
        /// <param name="podSpecPatch">PodSpecPatch holds strategic merge patch to apply against the artgc pod spec..</param>
        /// <param name="serviceAccountName">ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion.</param>
        /// <param name="strategy">Strategy is the strategy to use..</param>
        public IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC(bool forceFinalizerRemoval = default(bool), IoArgoprojWorkflowV1alpha1Metadata podMetadata = default(IoArgoprojWorkflowV1alpha1Metadata), string podSpecPatch = default(string), string serviceAccountName = default(string), string strategy = default(string))
        {
            this.ForceFinalizerRemoval = forceFinalizerRemoval;
            this.PodMetadata = podMetadata;
            this.PodSpecPatch = podSpecPatch;
            this.ServiceAccountName = serviceAccountName;
            this.Strategy = strategy;
        }

        /// <summary>
        /// ForceFinalizerRemoval: if set to true, the finalizer will be removed in the case that Artifact GC fails
        /// </summary>
        /// <value>ForceFinalizerRemoval: if set to true, the finalizer will be removed in the case that Artifact GC fails</value>
        [DataMember(Name = "forceFinalizerRemoval", EmitDefaultValue = true)]
        public bool ForceFinalizerRemoval { get; set; }

        /// <summary>
        /// Gets or Sets PodMetadata
        /// </summary>
        [DataMember(Name = "podMetadata", EmitDefaultValue = false)]
        public IoArgoprojWorkflowV1alpha1Metadata PodMetadata { get; set; }

        /// <summary>
        /// PodSpecPatch holds strategic merge patch to apply against the artgc pod spec.
        /// </summary>
        /// <value>PodSpecPatch holds strategic merge patch to apply against the artgc pod spec.</value>
        [DataMember(Name = "podSpecPatch", EmitDefaultValue = false)]
        public string PodSpecPatch { get; set; }

        /// <summary>
        /// ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion
        /// </summary>
        /// <value>ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion</value>
        [DataMember(Name = "serviceAccountName", EmitDefaultValue = false)]
        public string ServiceAccountName { get; set; }

        /// <summary>
        /// Strategy is the strategy to use.
        /// </summary>
        /// <value>Strategy is the strategy to use.</value>
        [DataMember(Name = "strategy", EmitDefaultValue = false)]
        public string Strategy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC {\n");
            sb.Append("  ForceFinalizerRemoval: ").Append(ForceFinalizerRemoval).Append("\n");
            sb.Append("  PodMetadata: ").Append(PodMetadata).Append("\n");
            sb.Append("  PodSpecPatch: ").Append(PodSpecPatch).Append("\n");
            sb.Append("  ServiceAccountName: ").Append(ServiceAccountName).Append("\n");
            sb.Append("  Strategy: ").Append(Strategy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
