/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// IoArgoprojEventsV1alpha1AzureServiceBusEventSource
    /// </summary>
    [DataContract(Name = "io.argoproj.events.v1alpha1.AzureServiceBusEventSource")]
    public partial class IoArgoprojEventsV1alpha1AzureServiceBusEventSource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IoArgoprojEventsV1alpha1AzureServiceBusEventSource" /> class.
        /// </summary>
        /// <param name="connectionString">connectionString.</param>
        /// <param name="filter">filter.</param>
        /// <param name="fullyQualifiedNamespace">fullyQualifiedNamespace.</param>
        /// <param name="jsonBody">jsonBody.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="queueName">queueName.</param>
        /// <param name="subscriptionName">subscriptionName.</param>
        /// <param name="tls">tls.</param>
        /// <param name="topicName">topicName.</param>
        public IoArgoprojEventsV1alpha1AzureServiceBusEventSource(IoK8sApiCoreV1SecretKeySelector connectionString = default(IoK8sApiCoreV1SecretKeySelector), IoArgoprojEventsV1alpha1EventSourceFilter filter = default(IoArgoprojEventsV1alpha1EventSourceFilter), string fullyQualifiedNamespace = default(string), bool jsonBody = default(bool), Dictionary<string, string> metadata = default(Dictionary<string, string>), string queueName = default(string), string subscriptionName = default(string), IoArgoprojEventsV1alpha1TLSConfig tls = default(IoArgoprojEventsV1alpha1TLSConfig), string topicName = default(string))
        {
            this.ConnectionString = connectionString;
            this.Filter = filter;
            this.FullyQualifiedNamespace = fullyQualifiedNamespace;
            this.JsonBody = jsonBody;
            this.Metadata = metadata;
            this.QueueName = queueName;
            this.SubscriptionName = subscriptionName;
            this.Tls = tls;
            this.TopicName = topicName;
        }

        /// <summary>
        /// Gets or Sets ConnectionString
        /// </summary>
        [DataMember(Name = "connectionString", EmitDefaultValue = false)]
        public IoK8sApiCoreV1SecretKeySelector ConnectionString { get; set; }

        /// <summary>
        /// Gets or Sets Filter
        /// </summary>
        [DataMember(Name = "filter", EmitDefaultValue = false)]
        public IoArgoprojEventsV1alpha1EventSourceFilter Filter { get; set; }

        /// <summary>
        /// Gets or Sets FullyQualifiedNamespace
        /// </summary>
        [DataMember(Name = "fullyQualifiedNamespace", EmitDefaultValue = false)]
        public string FullyQualifiedNamespace { get; set; }

        /// <summary>
        /// Gets or Sets JsonBody
        /// </summary>
        [DataMember(Name = "jsonBody", EmitDefaultValue = true)]
        public bool JsonBody { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// Gets or Sets QueueName
        /// </summary>
        [DataMember(Name = "queueName", EmitDefaultValue = false)]
        public string QueueName { get; set; }

        /// <summary>
        /// Gets or Sets SubscriptionName
        /// </summary>
        [DataMember(Name = "subscriptionName", EmitDefaultValue = false)]
        public string SubscriptionName { get; set; }

        /// <summary>
        /// Gets or Sets Tls
        /// </summary>
        [DataMember(Name = "tls", EmitDefaultValue = false)]
        public IoArgoprojEventsV1alpha1TLSConfig Tls { get; set; }

        /// <summary>
        /// Gets or Sets TopicName
        /// </summary>
        [DataMember(Name = "topicName", EmitDefaultValue = false)]
        public string TopicName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IoArgoprojEventsV1alpha1AzureServiceBusEventSource {\n");
            sb.Append("  ConnectionString: ").Append(ConnectionString).Append("\n");
            sb.Append("  Filter: ").Append(Filter).Append("\n");
            sb.Append("  FullyQualifiedNamespace: ").Append(FullyQualifiedNamespace).Append("\n");
            sb.Append("  JsonBody: ").Append(JsonBody).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  QueueName: ").Append(QueueName).Append("\n");
            sb.Append("  SubscriptionName: ").Append(SubscriptionName).Append("\n");
            sb.Append("  Tls: ").Append(Tls).Append("\n");
            sb.Append("  TopicName: ").Append(TopicName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
