/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// IoArgoprojEventsV1alpha1KafkaConsumerGroup
    /// </summary>
    [DataContract(Name = "io.argoproj.events.v1alpha1.KafkaConsumerGroup")]
    public partial class IoArgoprojEventsV1alpha1KafkaConsumerGroup : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IoArgoprojEventsV1alpha1KafkaConsumerGroup" /> class.
        /// </summary>
        /// <param name="groupName">groupName.</param>
        /// <param name="oldest">oldest.</param>
        /// <param name="rebalanceStrategy">rebalanceStrategy.</param>
        public IoArgoprojEventsV1alpha1KafkaConsumerGroup(string groupName = default(string), bool oldest = default(bool), string rebalanceStrategy = default(string))
        {
            this.GroupName = groupName;
            this.Oldest = oldest;
            this.RebalanceStrategy = rebalanceStrategy;
        }

        /// <summary>
        /// Gets or Sets GroupName
        /// </summary>
        [DataMember(Name = "groupName", EmitDefaultValue = false)]
        public string GroupName { get; set; }

        /// <summary>
        /// Gets or Sets Oldest
        /// </summary>
        [DataMember(Name = "oldest", EmitDefaultValue = true)]
        public bool Oldest { get; set; }

        /// <summary>
        /// Gets or Sets RebalanceStrategy
        /// </summary>
        [DataMember(Name = "rebalanceStrategy", EmitDefaultValue = false)]
        public string RebalanceStrategy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IoArgoprojEventsV1alpha1KafkaConsumerGroup {\n");
            sb.Append("  GroupName: ").Append(GroupName).Append("\n");
            sb.Append("  Oldest: ").Append(Oldest).Append("\n");
            sb.Append("  RebalanceStrategy: ").Append(RebalanceStrategy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
