/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// IoArgoprojEventsV1alpha1SASLConfig
    /// </summary>
    [DataContract(Name = "io.argoproj.events.v1alpha1.SASLConfig")]
    public partial class IoArgoprojEventsV1alpha1SASLConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IoArgoprojEventsV1alpha1SASLConfig" /> class.
        /// </summary>
        /// <param name="mechanism">mechanism.</param>
        /// <param name="passwordSecret">passwordSecret.</param>
        /// <param name="userSecret">userSecret.</param>
        public IoArgoprojEventsV1alpha1SASLConfig(string mechanism = default(string), IoK8sApiCoreV1SecretKeySelector passwordSecret = default(IoK8sApiCoreV1SecretKeySelector), IoK8sApiCoreV1SecretKeySelector userSecret = default(IoK8sApiCoreV1SecretKeySelector))
        {
            this.Mechanism = mechanism;
            this.PasswordSecret = passwordSecret;
            this.UserSecret = userSecret;
        }

        /// <summary>
        /// Gets or Sets Mechanism
        /// </summary>
        [DataMember(Name = "mechanism", EmitDefaultValue = false)]
        public string Mechanism { get; set; }

        /// <summary>
        /// Gets or Sets PasswordSecret
        /// </summary>
        [DataMember(Name = "passwordSecret", EmitDefaultValue = false)]
        public IoK8sApiCoreV1SecretKeySelector PasswordSecret { get; set; }

        /// <summary>
        /// Gets or Sets UserSecret
        /// </summary>
        [DataMember(Name = "userSecret", EmitDefaultValue = false)]
        public IoK8sApiCoreV1SecretKeySelector UserSecret { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IoArgoprojEventsV1alpha1SASLConfig {\n");
            sb.Append("  Mechanism: ").Append(Mechanism).Append("\n");
            sb.Append("  PasswordSecret: ").Append(PasswordSecret).Append("\n");
            sb.Append("  UserSecret: ").Append(UserSecret).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
