/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// IoArgoprojWorkflowV1alpha1ContainerSetTemplate
    /// </summary>
    [DataContract(Name = "io.argoproj.workflow.v1alpha1.ContainerSetTemplate")]
    public partial class IoArgoprojWorkflowV1alpha1ContainerSetTemplate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IoArgoprojWorkflowV1alpha1ContainerSetTemplate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IoArgoprojWorkflowV1alpha1ContainerSetTemplate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IoArgoprojWorkflowV1alpha1ContainerSetTemplate" /> class.
        /// </summary>
        /// <param name="containers">containers (required).</param>
        /// <param name="retryStrategy">retryStrategy.</param>
        /// <param name="volumeMounts">volumeMounts.</param>
        public IoArgoprojWorkflowV1alpha1ContainerSetTemplate(List<IoArgoprojWorkflowV1alpha1ContainerNode> containers = default(List<IoArgoprojWorkflowV1alpha1ContainerNode>), IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy retryStrategy = default(IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy), List<IoK8sApiCoreV1VolumeMount> volumeMounts = default(List<IoK8sApiCoreV1VolumeMount>))
        {
            // to ensure "containers" is required (not null)
            if (containers == null)
            {
                throw new ArgumentNullException("containers is a required property for IoArgoprojWorkflowV1alpha1ContainerSetTemplate and cannot be null");
            }
            this.Containers = containers;
            this.RetryStrategy = retryStrategy;
            this.VolumeMounts = volumeMounts;
        }

        /// <summary>
        /// Gets or Sets Containers
        /// </summary>
        [DataMember(Name = "containers", IsRequired = true, EmitDefaultValue = true)]
        public List<IoArgoprojWorkflowV1alpha1ContainerNode> Containers { get; set; }

        /// <summary>
        /// Gets or Sets RetryStrategy
        /// </summary>
        [DataMember(Name = "retryStrategy", EmitDefaultValue = false)]
        public IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy RetryStrategy { get; set; }

        /// <summary>
        /// Gets or Sets VolumeMounts
        /// </summary>
        [DataMember(Name = "volumeMounts", EmitDefaultValue = false)]
        public List<IoK8sApiCoreV1VolumeMount> VolumeMounts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IoArgoprojWorkflowV1alpha1ContainerSetTemplate {\n");
            sb.Append("  Containers: ").Append(Containers).Append("\n");
            sb.Append("  RetryStrategy: ").Append(RetryStrategy).Append("\n");
            sb.Append("  VolumeMounts: ").Append(VolumeMounts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
