/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// HTTPArtifact allows a file served on HTTP to be placed as an input artifact in a container
    /// </summary>
    [DataContract(Name = "io.argoproj.workflow.v1alpha1.HTTPArtifact")]
    public partial class IoArgoprojWorkflowV1alpha1HTTPArtifact : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IoArgoprojWorkflowV1alpha1HTTPArtifact" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IoArgoprojWorkflowV1alpha1HTTPArtifact() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IoArgoprojWorkflowV1alpha1HTTPArtifact" /> class.
        /// </summary>
        /// <param name="auth">auth.</param>
        /// <param name="headers">Headers are an optional list of headers to send with HTTP requests for artifacts.</param>
        /// <param name="url">URL of the artifact (required).</param>
        public IoArgoprojWorkflowV1alpha1HTTPArtifact(IoArgoprojWorkflowV1alpha1HTTPAuth auth = default(IoArgoprojWorkflowV1alpha1HTTPAuth), List<IoArgoprojWorkflowV1alpha1Header> headers = default(List<IoArgoprojWorkflowV1alpha1Header>), string url = default(string))
        {
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for IoArgoprojWorkflowV1alpha1HTTPArtifact and cannot be null");
            }
            this.Url = url;
            this.Auth = auth;
            this.Headers = headers;
        }

        /// <summary>
        /// Gets or Sets Auth
        /// </summary>
        [DataMember(Name = "auth", EmitDefaultValue = false)]
        public IoArgoprojWorkflowV1alpha1HTTPAuth Auth { get; set; }

        /// <summary>
        /// Headers are an optional list of headers to send with HTTP requests for artifacts
        /// </summary>
        /// <value>Headers are an optional list of headers to send with HTTP requests for artifacts</value>
        [DataMember(Name = "headers", EmitDefaultValue = false)]
        public List<IoArgoprojWorkflowV1alpha1Header> Headers { get; set; }

        /// <summary>
        /// URL of the artifact
        /// </summary>
        /// <value>URL of the artifact</value>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IoArgoprojWorkflowV1alpha1HTTPArtifact {\n");
            sb.Append("  Auth: ").Append(Auth).Append("\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
