/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// OwnerReference contains enough information to let you identify an owning object. An owning object must be in the same namespace as the dependent, or be cluster-scoped, so there is no namespace field.
    /// </summary>
    [DataContract(Name = "io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference")]
    public partial class IoK8sApimachineryPkgApisMetaV1OwnerReference : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IoK8sApimachineryPkgApisMetaV1OwnerReference" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IoK8sApimachineryPkgApisMetaV1OwnerReference() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IoK8sApimachineryPkgApisMetaV1OwnerReference" /> class.
        /// </summary>
        /// <param name="apiVersion">API version of the referent. (required).</param>
        /// <param name="blockOwnerDeletion">If true, AND if the owner has the \&quot;foregroundDeletion\&quot; finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. Defaults to false. To set this field, a user needs \&quot;delete\&quot; permission of the owner, otherwise 422 (Unprocessable Entity) will be returned..</param>
        /// <param name="controller">If true, this reference points to the managing controller..</param>
        /// <param name="kind">Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds (required).</param>
        /// <param name="name">Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names (required).</param>
        /// <param name="uid">UID of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#uids (required).</param>
        public IoK8sApimachineryPkgApisMetaV1OwnerReference(string apiVersion = default(string), bool blockOwnerDeletion = default(bool), bool controller = default(bool), string kind = default(string), string name = default(string), string uid = default(string))
        {
            // to ensure "apiVersion" is required (not null)
            if (apiVersion == null)
            {
                throw new ArgumentNullException("apiVersion is a required property for IoK8sApimachineryPkgApisMetaV1OwnerReference and cannot be null");
            }
            this.ApiVersion = apiVersion;
            // to ensure "kind" is required (not null)
            if (kind == null)
            {
                throw new ArgumentNullException("kind is a required property for IoK8sApimachineryPkgApisMetaV1OwnerReference and cannot be null");
            }
            this.Kind = kind;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for IoK8sApimachineryPkgApisMetaV1OwnerReference and cannot be null");
            }
            this.Name = name;
            // to ensure "uid" is required (not null)
            if (uid == null)
            {
                throw new ArgumentNullException("uid is a required property for IoK8sApimachineryPkgApisMetaV1OwnerReference and cannot be null");
            }
            this.Uid = uid;
            this.BlockOwnerDeletion = blockOwnerDeletion;
            this.Controller = controller;
        }

        /// <summary>
        /// API version of the referent.
        /// </summary>
        /// <value>API version of the referent.</value>
        [DataMember(Name = "apiVersion", IsRequired = true, EmitDefaultValue = true)]
        public string ApiVersion { get; set; }

        /// <summary>
        /// If true, AND if the owner has the \&quot;foregroundDeletion\&quot; finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. Defaults to false. To set this field, a user needs \&quot;delete\&quot; permission of the owner, otherwise 422 (Unprocessable Entity) will be returned.
        /// </summary>
        /// <value>If true, AND if the owner has the \&quot;foregroundDeletion\&quot; finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. Defaults to false. To set this field, a user needs \&quot;delete\&quot; permission of the owner, otherwise 422 (Unprocessable Entity) will be returned.</value>
        [DataMember(Name = "blockOwnerDeletion", EmitDefaultValue = true)]
        public bool BlockOwnerDeletion { get; set; }

        /// <summary>
        /// If true, this reference points to the managing controller.
        /// </summary>
        /// <value>If true, this reference points to the managing controller.</value>
        [DataMember(Name = "controller", EmitDefaultValue = true)]
        public bool Controller { get; set; }

        /// <summary>
        /// Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        /// </summary>
        /// <value>Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds</value>
        [DataMember(Name = "kind", IsRequired = true, EmitDefaultValue = true)]
        public string Kind { get; set; }

        /// <summary>
        /// Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names
        /// </summary>
        /// <value>Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// UID of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#uids
        /// </summary>
        /// <value>UID of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#uids</value>
        [DataMember(Name = "uid", IsRequired = true, EmitDefaultValue = true)]
        public string Uid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IoK8sApimachineryPkgApisMetaV1OwnerReference {\n");
            sb.Append("  ApiVersion: ").Append(ApiVersion).Append("\n");
            sb.Append("  BlockOwnerDeletion: ").Append(BlockOwnerDeletion).Append("\n");
            sb.Append("  Controller: ").Append(Controller).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Uid: ").Append(Uid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
