@wfapi_HostAddress = http://localhost:2746
@wfapi_Token = eyJhbGciOiJSUzI1NiIsImtpZCI6Ino1aGlwS1pOamZFeDVOYnQzdktvcV9xcC1XWi1zamdDVkEyMEEzaWxGWjQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6IndmYXBpLnNlcnZpY2UtYWNjb3VudC10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJ3ZmFwaSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijk3N2MxOTYwLTU3ODctNGE0MS04NDYxLWNjZGQzOGE2MWVhYiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDphcmdvOndmYXBpIn0.KaBh6yav-HDh1NXOjIfS7mluPcX3pYsjbGf1YikBq035EOjA7JQ2EbrSzTVVX1Y7l8d3DW7UrSysMz4oUlAacxGA-B4V07JvwbWtaQgMHOJFgwHxMYztJtpI2Inemqq2gBIKQrqPaiksc6jaogPZqYsD6gzy6qF6gOwCnew-FWDMeXBsIyIWcmbpPVqgEnp2f0Q7mPDjK3FbciLwfuHnjbE_NplTGHNS6cZeMoNFoRIL5bsT2eq6SihPJqxHCwTSfcgTTN1v_zAaC6tEvDSlgo6zO8q7XYjzc5-Mx1GhDrXEu7o2u5wmBtsFupgA9mthhE1OI1gk-6O3XqJNTVSQRg

GET {{wfapi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{wfapi_HostAddress}}/api/v1/workflows/argo/hello-world-ngfvb/log
Accept: application/json
Authorization: Bearer {{wfapi_Token}}

###

GET {{wfapi_HostAddress}}/api/v1/workflows/argo/hello-world-ngfvb/log?podName=hello-world-ngfvb
Accept: application/json
Authorization: Bearer {{wfapi_Token}}

###

GET {{wfapi_HostAddress}}/api/v1/workflows/argo/hello-world-ngfvb/log?podName=hello-world-ngfvb&logOptions.container=main
Accept: application/json
Authorization: Bearer {{wfapi_Token}}

###

GET {{wfapi_HostAddress}}/api/v1/workflows/argo/hello-world-ngfvb/log?podName=hello-world-ngfvb&logOptions.container=main&logOptions.follow=true
Accept: application/json
Authorization: Bearer {{wfapi_Token}}
