@startuml c4-container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(end_user, "End User", "A person or NPE using the system")

System_Boundary(k8s, "Kubernetes Cluster", $descr="Note: Authservice is shown multiple times for clarity only. There is only one deployment of Authservice as part of UDS Core.") {
    System_Boundary(uds_core, "UDS Core") {
        Container_Ext(keycloak, "Keycloak")
    }
    System_Boundary(mission_app_ns, "Mission App Namespace") {
        Container_Ext(mission_app_authservice, "Authservice")
        Container_Ext(mission_app, "Mission App")
    }
    System_Boundary(argo_namespace, "Argo Namespace") {
        Container_Ext(wfapi_authservice, "Authservice")
        Container(wfapi, "WF API")
        Container_Ext(argo_server, "Argo Server")
    }

    Container_Ext(k8s_api1, "K8s API")
    Container_Ext(k8s_api2, "K8s API")
}

Lay_R(end_user, k8s)
Lay_D(uds_core, mission_app_ns)
Lay_D(mission_app_ns, argo_namespace)
Rel_R(end_user, mission_app_authservice, "HTTPS")
Rel_U(mission_app_authservice, keycloak, "w/o JWT", "Redirect if person, reject if NPE")
Rel_R(mission_app_authservice, mission_app, "w/ JWT")
Rel_R(mission_app, wfapi_authservice, "HTTPS w/ JWT", "Mission App must go through the Istio Gateway, NetPols block direct comms. JWT is passed through.")
Rel_R(wfapi_authservice, wfapi, "w/ JWT", "Don't redirect to Keycloak if no JWT, just reject")
Rel_R(wfapi, argo_server, "K8s Access Token", "Primary")
Rel_D(wfapi, k8s_api1, "K8s Access Token", "Secondary, prefer using Argo Server")
Rel_D(argo_server, k8s_api2, "K8s Access Token")

SHOW_FLOATING_LEGEND()
Lay_D(end_user, LEGEND())
@enduml
