/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojEventsV1alpha1KafkaEventSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojEventsV1alpha1KafkaEventSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojEventsV1alpha1KafkaEventSource
        //private IoArgoprojEventsV1alpha1KafkaEventSource instance;

        public IoArgoprojEventsV1alpha1KafkaEventSourceTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojEventsV1alpha1KafkaEventSource
            //instance = new IoArgoprojEventsV1alpha1KafkaEventSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojEventsV1alpha1KafkaEventSource
        /// </summary>
        [Fact]
        public void IoArgoprojEventsV1alpha1KafkaEventSourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojEventsV1alpha1KafkaEventSource
            //Assert.IsType<IoArgoprojEventsV1alpha1KafkaEventSource>(instance);
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }

        /// <summary>
        /// Test the property 'ConnectionBackoff'
        /// </summary>
        [Fact]
        public void ConnectionBackoffTest()
        {
            // TODO unit test for the property 'ConnectionBackoff'
        }

        /// <summary>
        /// Test the property 'ConsumerGroup'
        /// </summary>
        [Fact]
        public void ConsumerGroupTest()
        {
            // TODO unit test for the property 'ConsumerGroup'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'JsonBody'
        /// </summary>
        [Fact]
        public void JsonBodyTest()
        {
            // TODO unit test for the property 'JsonBody'
        }

        /// <summary>
        /// Test the property 'LimitEventsPerSecond'
        /// </summary>
        [Fact]
        public void LimitEventsPerSecondTest()
        {
            // TODO unit test for the property 'LimitEventsPerSecond'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Partition'
        /// </summary>
        [Fact]
        public void PartitionTest()
        {
            // TODO unit test for the property 'Partition'
        }

        /// <summary>
        /// Test the property 'Sasl'
        /// </summary>
        [Fact]
        public void SaslTest()
        {
            // TODO unit test for the property 'Sasl'
        }

        /// <summary>
        /// Test the property 'Tls'
        /// </summary>
        [Fact]
        public void TlsTest()
        {
            // TODO unit test for the property 'Tls'
        }

        /// <summary>
        /// Test the property 'Topic'
        /// </summary>
        [Fact]
        public void TopicTest()
        {
            // TODO unit test for the property 'Topic'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
