/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojWorkflowV1alpha1UserContainer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojWorkflowV1alpha1UserContainerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojWorkflowV1alpha1UserContainer
        //private IoArgoprojWorkflowV1alpha1UserContainer instance;

        public IoArgoprojWorkflowV1alpha1UserContainerTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojWorkflowV1alpha1UserContainer
            //instance = new IoArgoprojWorkflowV1alpha1UserContainer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojWorkflowV1alpha1UserContainer
        /// </summary>
        [Fact]
        public void IoArgoprojWorkflowV1alpha1UserContainerInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojWorkflowV1alpha1UserContainer
            //Assert.IsType<IoArgoprojWorkflowV1alpha1UserContainer>(instance);
        }

        /// <summary>
        /// Test the property 'Args'
        /// </summary>
        [Fact]
        public void ArgsTest()
        {
            // TODO unit test for the property 'Args'
        }

        /// <summary>
        /// Test the property 'Command'
        /// </summary>
        [Fact]
        public void CommandTest()
        {
            // TODO unit test for the property 'Command'
        }

        /// <summary>
        /// Test the property 'Env'
        /// </summary>
        [Fact]
        public void EnvTest()
        {
            // TODO unit test for the property 'Env'
        }

        /// <summary>
        /// Test the property 'EnvFrom'
        /// </summary>
        [Fact]
        public void EnvFromTest()
        {
            // TODO unit test for the property 'EnvFrom'
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

        /// <summary>
        /// Test the property 'ImagePullPolicy'
        /// </summary>
        [Fact]
        public void ImagePullPolicyTest()
        {
            // TODO unit test for the property 'ImagePullPolicy'
        }

        /// <summary>
        /// Test the property 'Lifecycle'
        /// </summary>
        [Fact]
        public void LifecycleTest()
        {
            // TODO unit test for the property 'Lifecycle'
        }

        /// <summary>
        /// Test the property 'LivenessProbe'
        /// </summary>
        [Fact]
        public void LivenessProbeTest()
        {
            // TODO unit test for the property 'LivenessProbe'
        }

        /// <summary>
        /// Test the property 'MirrorVolumeMounts'
        /// </summary>
        [Fact]
        public void MirrorVolumeMountsTest()
        {
            // TODO unit test for the property 'MirrorVolumeMounts'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Ports'
        /// </summary>
        [Fact]
        public void PortsTest()
        {
            // TODO unit test for the property 'Ports'
        }

        /// <summary>
        /// Test the property 'ReadinessProbe'
        /// </summary>
        [Fact]
        public void ReadinessProbeTest()
        {
            // TODO unit test for the property 'ReadinessProbe'
        }

        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Fact]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }

        /// <summary>
        /// Test the property 'SecurityContext'
        /// </summary>
        [Fact]
        public void SecurityContextTest()
        {
            // TODO unit test for the property 'SecurityContext'
        }

        /// <summary>
        /// Test the property 'StartupProbe'
        /// </summary>
        [Fact]
        public void StartupProbeTest()
        {
            // TODO unit test for the property 'StartupProbe'
        }

        /// <summary>
        /// Test the property 'Stdin'
        /// </summary>
        [Fact]
        public void StdinTest()
        {
            // TODO unit test for the property 'Stdin'
        }

        /// <summary>
        /// Test the property 'StdinOnce'
        /// </summary>
        [Fact]
        public void StdinOnceTest()
        {
            // TODO unit test for the property 'StdinOnce'
        }

        /// <summary>
        /// Test the property 'TerminationMessagePath'
        /// </summary>
        [Fact]
        public void TerminationMessagePathTest()
        {
            // TODO unit test for the property 'TerminationMessagePath'
        }

        /// <summary>
        /// Test the property 'TerminationMessagePolicy'
        /// </summary>
        [Fact]
        public void TerminationMessagePolicyTest()
        {
            // TODO unit test for the property 'TerminationMessagePolicy'
        }

        /// <summary>
        /// Test the property 'Tty'
        /// </summary>
        [Fact]
        public void TtyTest()
        {
            // TODO unit test for the property 'Tty'
        }

        /// <summary>
        /// Test the property 'VolumeDevices'
        /// </summary>
        [Fact]
        public void VolumeDevicesTest()
        {
            // TODO unit test for the property 'VolumeDevices'
        }

        /// <summary>
        /// Test the property 'VolumeMounts'
        /// </summary>
        [Fact]
        public void VolumeMountsTest()
        {
            // TODO unit test for the property 'VolumeMounts'
        }

        /// <summary>
        /// Test the property 'WorkingDir'
        /// </summary>
        [Fact]
        public void WorkingDirTest()
        {
            // TODO unit test for the property 'WorkingDir'
        }
    }
}
