/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojWorkflowV1alpha1Version
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojWorkflowV1alpha1VersionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojWorkflowV1alpha1Version
        //private IoArgoprojWorkflowV1alpha1Version instance;

        public IoArgoprojWorkflowV1alpha1VersionTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojWorkflowV1alpha1Version
            //instance = new IoArgoprojWorkflowV1alpha1Version();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojWorkflowV1alpha1Version
        /// </summary>
        [Fact]
        public void IoArgoprojWorkflowV1alpha1VersionInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojWorkflowV1alpha1Version
            //Assert.IsType<IoArgoprojWorkflowV1alpha1Version>(instance);
        }

        /// <summary>
        /// Test the property 'BuildDate'
        /// </summary>
        [Fact]
        public void BuildDateTest()
        {
            // TODO unit test for the property 'BuildDate'
        }

        /// <summary>
        /// Test the property 'Compiler'
        /// </summary>
        [Fact]
        public void CompilerTest()
        {
            // TODO unit test for the property 'Compiler'
        }

        /// <summary>
        /// Test the property 'GitCommit'
        /// </summary>
        [Fact]
        public void GitCommitTest()
        {
            // TODO unit test for the property 'GitCommit'
        }

        /// <summary>
        /// Test the property 'GitTag'
        /// </summary>
        [Fact]
        public void GitTagTest()
        {
            // TODO unit test for the property 'GitTag'
        }

        /// <summary>
        /// Test the property 'GitTreeState'
        /// </summary>
        [Fact]
        public void GitTreeStateTest()
        {
            // TODO unit test for the property 'GitTreeState'
        }

        /// <summary>
        /// Test the property 'GoVersion'
        /// </summary>
        [Fact]
        public void GoVersionTest()
        {
            // TODO unit test for the property 'GoVersion'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
