/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojEventsV1alpha1EventDependencyFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojEventsV1alpha1EventDependencyFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojEventsV1alpha1EventDependencyFilter
        //private IoArgoprojEventsV1alpha1EventDependencyFilter instance;

        public IoArgoprojEventsV1alpha1EventDependencyFilterTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojEventsV1alpha1EventDependencyFilter
            //instance = new IoArgoprojEventsV1alpha1EventDependencyFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojEventsV1alpha1EventDependencyFilter
        /// </summary>
        [Fact]
        public void IoArgoprojEventsV1alpha1EventDependencyFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojEventsV1alpha1EventDependencyFilter
            //Assert.IsType<IoArgoprojEventsV1alpha1EventDependencyFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'DataLogicalOperator'
        /// </summary>
        [Fact]
        public void DataLogicalOperatorTest()
        {
            // TODO unit test for the property 'DataLogicalOperator'
        }

        /// <summary>
        /// Test the property 'ExprLogicalOperator'
        /// </summary>
        [Fact]
        public void ExprLogicalOperatorTest()
        {
            // TODO unit test for the property 'ExprLogicalOperator'
        }

        /// <summary>
        /// Test the property 'Exprs'
        /// </summary>
        [Fact]
        public void ExprsTest()
        {
            // TODO unit test for the property 'Exprs'
        }

        /// <summary>
        /// Test the property 'Script'
        /// </summary>
        [Fact]
        public void ScriptTest()
        {
            // TODO unit test for the property 'Script'
        }

        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
    }
}
