/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojEventsV1alpha1SFTPEventSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojEventsV1alpha1SFTPEventSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojEventsV1alpha1SFTPEventSource
        //private IoArgoprojEventsV1alpha1SFTPEventSource instance;

        public IoArgoprojEventsV1alpha1SFTPEventSourceTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojEventsV1alpha1SFTPEventSource
            //instance = new IoArgoprojEventsV1alpha1SFTPEventSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojEventsV1alpha1SFTPEventSource
        /// </summary>
        [Fact]
        public void IoArgoprojEventsV1alpha1SFTPEventSourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojEventsV1alpha1SFTPEventSource
            //Assert.IsType<IoArgoprojEventsV1alpha1SFTPEventSource>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'PollIntervalDuration'
        /// </summary>
        [Fact]
        public void PollIntervalDurationTest()
        {
            // TODO unit test for the property 'PollIntervalDuration'
        }

        /// <summary>
        /// Test the property 'SshKeySecret'
        /// </summary>
        [Fact]
        public void SshKeySecretTest()
        {
            // TODO unit test for the property 'SshKeySecret'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'WatchPathConfig'
        /// </summary>
        [Fact]
        public void WatchPathConfigTest()
        {
            // TODO unit test for the property 'WatchPathConfig'
        }
    }
}
