/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoK8sApiCoreV1PortworxVolumeSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoK8sApiCoreV1PortworxVolumeSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoK8sApiCoreV1PortworxVolumeSource
        //private IoK8sApiCoreV1PortworxVolumeSource instance;

        public IoK8sApiCoreV1PortworxVolumeSourceTests()
        {
            // TODO uncomment below to create an instance of IoK8sApiCoreV1PortworxVolumeSource
            //instance = new IoK8sApiCoreV1PortworxVolumeSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoK8sApiCoreV1PortworxVolumeSource
        /// </summary>
        [Fact]
        public void IoK8sApiCoreV1PortworxVolumeSourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoK8sApiCoreV1PortworxVolumeSource
            //Assert.IsType<IoK8sApiCoreV1PortworxVolumeSource>(instance);
        }

        /// <summary>
        /// Test the property 'FsType'
        /// </summary>
        [Fact]
        public void FsTypeTest()
        {
            // TODO unit test for the property 'FsType'
        }

        /// <summary>
        /// Test the property 'ReadOnly'
        /// </summary>
        [Fact]
        public void ReadOnlyTest()
        {
            // TODO unit test for the property 'ReadOnly'
        }

        /// <summary>
        /// Test the property 'VolumeID'
        /// </summary>
        [Fact]
        public void VolumeIDTest()
        {
            // TODO unit test for the property 'VolumeID'
        }
    }
}
