/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing EventsourceEventSourceWatchEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventsourceEventSourceWatchEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventsourceEventSourceWatchEvent
        //private EventsourceEventSourceWatchEvent instance;

        public EventsourceEventSourceWatchEventTests()
        {
            // TODO uncomment below to create an instance of EventsourceEventSourceWatchEvent
            //instance = new EventsourceEventSourceWatchEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventsourceEventSourceWatchEvent
        /// </summary>
        [Fact]
        public void EventsourceEventSourceWatchEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventsourceEventSourceWatchEvent
            //Assert.IsType<EventsourceEventSourceWatchEvent>(instance);
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
