/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojEventsV1alpha1NATSTrigger
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojEventsV1alpha1NATSTriggerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojEventsV1alpha1NATSTrigger
        //private IoArgoprojEventsV1alpha1NATSTrigger instance;

        public IoArgoprojEventsV1alpha1NATSTriggerTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojEventsV1alpha1NATSTrigger
            //instance = new IoArgoprojEventsV1alpha1NATSTrigger();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojEventsV1alpha1NATSTrigger
        /// </summary>
        [Fact]
        public void IoArgoprojEventsV1alpha1NATSTriggerInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojEventsV1alpha1NATSTrigger
            //Assert.IsType<IoArgoprojEventsV1alpha1NATSTrigger>(instance);
        }

        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Fact]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'Tls'
        /// </summary>
        [Fact]
        public void TlsTest()
        {
            // TODO unit test for the property 'Tls'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
