/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojWorkflowV1alpha1HTTPBodySource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojWorkflowV1alpha1HTTPBodySourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojWorkflowV1alpha1HTTPBodySource
        //private IoArgoprojWorkflowV1alpha1HTTPBodySource instance;

        public IoArgoprojWorkflowV1alpha1HTTPBodySourceTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojWorkflowV1alpha1HTTPBodySource
            //instance = new IoArgoprojWorkflowV1alpha1HTTPBodySource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojWorkflowV1alpha1HTTPBodySource
        /// </summary>
        [Fact]
        public void IoArgoprojWorkflowV1alpha1HTTPBodySourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojWorkflowV1alpha1HTTPBodySource
            //Assert.IsType<IoArgoprojWorkflowV1alpha1HTTPBodySource>(instance);
        }

        /// <summary>
        /// Test the property 'Bytes'
        /// </summary>
        [Fact]
        public void BytesTest()
        {
            // TODO unit test for the property 'Bytes'
        }
    }
}
