/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoK8sApiCoreV1PersistentVolumeClaimSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoK8sApiCoreV1PersistentVolumeClaimSpecTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoK8sApiCoreV1PersistentVolumeClaimSpec
        //private IoK8sApiCoreV1PersistentVolumeClaimSpec instance;

        public IoK8sApiCoreV1PersistentVolumeClaimSpecTests()
        {
            // TODO uncomment below to create an instance of IoK8sApiCoreV1PersistentVolumeClaimSpec
            //instance = new IoK8sApiCoreV1PersistentVolumeClaimSpec();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoK8sApiCoreV1PersistentVolumeClaimSpec
        /// </summary>
        [Fact]
        public void IoK8sApiCoreV1PersistentVolumeClaimSpecInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoK8sApiCoreV1PersistentVolumeClaimSpec
            //Assert.IsType<IoK8sApiCoreV1PersistentVolumeClaimSpec>(instance);
        }

        /// <summary>
        /// Test the property 'AccessModes'
        /// </summary>
        [Fact]
        public void AccessModesTest()
        {
            // TODO unit test for the property 'AccessModes'
        }

        /// <summary>
        /// Test the property 'DataSource'
        /// </summary>
        [Fact]
        public void DataSourceTest()
        {
            // TODO unit test for the property 'DataSource'
        }

        /// <summary>
        /// Test the property 'DataSourceRef'
        /// </summary>
        [Fact]
        public void DataSourceRefTest()
        {
            // TODO unit test for the property 'DataSourceRef'
        }

        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Fact]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }

        /// <summary>
        /// Test the property 'Selector'
        /// </summary>
        [Fact]
        public void SelectorTest()
        {
            // TODO unit test for the property 'Selector'
        }

        /// <summary>
        /// Test the property 'StorageClassName'
        /// </summary>
        [Fact]
        public void StorageClassNameTest()
        {
            // TODO unit test for the property 'StorageClassName'
        }

        /// <summary>
        /// Test the property 'VolumeMode'
        /// </summary>
        [Fact]
        public void VolumeModeTest()
        {
            // TODO unit test for the property 'VolumeMode'
        }

        /// <summary>
        /// Test the property 'VolumeName'
        /// </summary>
        [Fact]
        public void VolumeNameTest()
        {
            // TODO unit test for the property 'VolumeName'
        }
    }
}
