/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojWorkflowV1alpha1WorkflowCreateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojWorkflowV1alpha1WorkflowCreateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojWorkflowV1alpha1WorkflowCreateRequest
        //private IoArgoprojWorkflowV1alpha1WorkflowCreateRequest instance;

        public IoArgoprojWorkflowV1alpha1WorkflowCreateRequestTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojWorkflowV1alpha1WorkflowCreateRequest
            //instance = new IoArgoprojWorkflowV1alpha1WorkflowCreateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojWorkflowV1alpha1WorkflowCreateRequest
        /// </summary>
        [Fact]
        public void IoArgoprojWorkflowV1alpha1WorkflowCreateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojWorkflowV1alpha1WorkflowCreateRequest
            //Assert.IsType<IoArgoprojWorkflowV1alpha1WorkflowCreateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'CreateOptions'
        /// </summary>
        [Fact]
        public void CreateOptionsTest()
        {
            // TODO unit test for the property 'CreateOptions'
        }

        /// <summary>
        /// Test the property 'InstanceID'
        /// </summary>
        [Fact]
        public void InstanceIDTest()
        {
            // TODO unit test for the property 'InstanceID'
        }

        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }

        /// <summary>
        /// Test the property 'ServerDryRun'
        /// </summary>
        [Fact]
        public void ServerDryRunTest()
        {
            // TODO unit test for the property 'ServerDryRun'
        }

        /// <summary>
        /// Test the property 'Workflow'
        /// </summary>
        [Fact]
        public void WorkflowTest()
        {
            // TODO unit test for the property 'Workflow'
        }
    }
}
