/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojWorkflowV1alpha1OAuth2Auth
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojWorkflowV1alpha1OAuth2AuthTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojWorkflowV1alpha1OAuth2Auth
        //private IoArgoprojWorkflowV1alpha1OAuth2Auth instance;

        public IoArgoprojWorkflowV1alpha1OAuth2AuthTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojWorkflowV1alpha1OAuth2Auth
            //instance = new IoArgoprojWorkflowV1alpha1OAuth2Auth();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojWorkflowV1alpha1OAuth2Auth
        /// </summary>
        [Fact]
        public void IoArgoprojWorkflowV1alpha1OAuth2AuthInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojWorkflowV1alpha1OAuth2Auth
            //Assert.IsType<IoArgoprojWorkflowV1alpha1OAuth2Auth>(instance);
        }

        /// <summary>
        /// Test the property 'ClientIDSecret'
        /// </summary>
        [Fact]
        public void ClientIDSecretTest()
        {
            // TODO unit test for the property 'ClientIDSecret'
        }

        /// <summary>
        /// Test the property 'ClientSecretSecret'
        /// </summary>
        [Fact]
        public void ClientSecretSecretTest()
        {
            // TODO unit test for the property 'ClientSecretSecret'
        }

        /// <summary>
        /// Test the property 'EndpointParams'
        /// </summary>
        [Fact]
        public void EndpointParamsTest()
        {
            // TODO unit test for the property 'EndpointParams'
        }

        /// <summary>
        /// Test the property 'Scopes'
        /// </summary>
        [Fact]
        public void ScopesTest()
        {
            // TODO unit test for the property 'Scopes'
        }

        /// <summary>
        /// Test the property 'TokenURLSecret'
        /// </summary>
        [Fact]
        public void TokenURLSecretTest()
        {
            // TODO unit test for the property 'TokenURLSecret'
        }
    }
}
