/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojEventsV1alpha1BitbucketServerEventSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojEventsV1alpha1BitbucketServerEventSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojEventsV1alpha1BitbucketServerEventSource
        //private IoArgoprojEventsV1alpha1BitbucketServerEventSource instance;

        public IoArgoprojEventsV1alpha1BitbucketServerEventSourceTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojEventsV1alpha1BitbucketServerEventSource
            //instance = new IoArgoprojEventsV1alpha1BitbucketServerEventSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojEventsV1alpha1BitbucketServerEventSource
        /// </summary>
        [Fact]
        public void IoArgoprojEventsV1alpha1BitbucketServerEventSourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojEventsV1alpha1BitbucketServerEventSource
            //Assert.IsType<IoArgoprojEventsV1alpha1BitbucketServerEventSource>(instance);
        }

        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }

        /// <summary>
        /// Test the property 'BitbucketserverBaseURL'
        /// </summary>
        [Fact]
        public void BitbucketserverBaseURLTest()
        {
            // TODO unit test for the property 'BitbucketserverBaseURL'
        }

        /// <summary>
        /// Test the property 'DeleteHookOnFinish'
        /// </summary>
        [Fact]
        public void DeleteHookOnFinishTest()
        {
            // TODO unit test for the property 'DeleteHookOnFinish'
        }

        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'ProjectKey'
        /// </summary>
        [Fact]
        public void ProjectKeyTest()
        {
            // TODO unit test for the property 'ProjectKey'
        }

        /// <summary>
        /// Test the property 'Repositories'
        /// </summary>
        [Fact]
        public void RepositoriesTest()
        {
            // TODO unit test for the property 'Repositories'
        }

        /// <summary>
        /// Test the property 'RepositorySlug'
        /// </summary>
        [Fact]
        public void RepositorySlugTest()
        {
            // TODO unit test for the property 'RepositorySlug'
        }

        /// <summary>
        /// Test the property 'Tls'
        /// </summary>
        [Fact]
        public void TlsTest()
        {
            // TODO unit test for the property 'Tls'
        }

        /// <summary>
        /// Test the property 'Webhook'
        /// </summary>
        [Fact]
        public void WebhookTest()
        {
            // TODO unit test for the property 'Webhook'
        }

        /// <summary>
        /// Test the property 'WebhookSecret'
        /// </summary>
        [Fact]
        public void WebhookSecretTest()
        {
            // TODO unit test for the property 'WebhookSecret'
        }
    }
}
