/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojEventsV1alpha1StorageGridEventSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojEventsV1alpha1StorageGridEventSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojEventsV1alpha1StorageGridEventSource
        //private IoArgoprojEventsV1alpha1StorageGridEventSource instance;

        public IoArgoprojEventsV1alpha1StorageGridEventSourceTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojEventsV1alpha1StorageGridEventSource
            //instance = new IoArgoprojEventsV1alpha1StorageGridEventSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojEventsV1alpha1StorageGridEventSource
        /// </summary>
        [Fact]
        public void IoArgoprojEventsV1alpha1StorageGridEventSourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojEventsV1alpha1StorageGridEventSource
            //Assert.IsType<IoArgoprojEventsV1alpha1StorageGridEventSource>(instance);
        }

        /// <summary>
        /// Test the property 'ApiURL'
        /// </summary>
        [Fact]
        public void ApiURLTest()
        {
            // TODO unit test for the property 'ApiURL'
        }

        /// <summary>
        /// Test the property 'AuthToken'
        /// </summary>
        [Fact]
        public void AuthTokenTest()
        {
            // TODO unit test for the property 'AuthToken'
        }

        /// <summary>
        /// Test the property 'Bucket'
        /// </summary>
        [Fact]
        public void BucketTest()
        {
            // TODO unit test for the property 'Bucket'
        }

        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }

        /// <summary>
        /// Test the property 'TopicArn'
        /// </summary>
        [Fact]
        public void TopicArnTest()
        {
            // TODO unit test for the property 'TopicArn'
        }

        /// <summary>
        /// Test the property 'Webhook'
        /// </summary>
        [Fact]
        public void WebhookTest()
        {
            // TODO unit test for the property 'Webhook'
        }
    }
}
