/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojWorkflowV1alpha1InfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojWorkflowV1alpha1InfoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojWorkflowV1alpha1InfoResponse
        //private IoArgoprojWorkflowV1alpha1InfoResponse instance;

        public IoArgoprojWorkflowV1alpha1InfoResponseTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojWorkflowV1alpha1InfoResponse
            //instance = new IoArgoprojWorkflowV1alpha1InfoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojWorkflowV1alpha1InfoResponse
        /// </summary>
        [Fact]
        public void IoArgoprojWorkflowV1alpha1InfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojWorkflowV1alpha1InfoResponse
            //Assert.IsType<IoArgoprojWorkflowV1alpha1InfoResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Columns'
        /// </summary>
        [Fact]
        public void ColumnsTest()
        {
            // TODO unit test for the property 'Columns'
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

        /// <summary>
        /// Test the property 'ManagedNamespace'
        /// </summary>
        [Fact]
        public void ManagedNamespaceTest()
        {
            // TODO unit test for the property 'ManagedNamespace'
        }

        /// <summary>
        /// Test the property 'Modals'
        /// </summary>
        [Fact]
        public void ModalsTest()
        {
            // TODO unit test for the property 'Modals'
        }

        /// <summary>
        /// Test the property 'NavColor'
        /// </summary>
        [Fact]
        public void NavColorTest()
        {
            // TODO unit test for the property 'NavColor'
        }
    }
}
