/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojEventsV1alpha1PulsarEventSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojEventsV1alpha1PulsarEventSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojEventsV1alpha1PulsarEventSource
        //private IoArgoprojEventsV1alpha1PulsarEventSource instance;

        public IoArgoprojEventsV1alpha1PulsarEventSourceTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojEventsV1alpha1PulsarEventSource
            //instance = new IoArgoprojEventsV1alpha1PulsarEventSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojEventsV1alpha1PulsarEventSource
        /// </summary>
        [Fact]
        public void IoArgoprojEventsV1alpha1PulsarEventSourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojEventsV1alpha1PulsarEventSource
            //Assert.IsType<IoArgoprojEventsV1alpha1PulsarEventSource>(instance);
        }

        /// <summary>
        /// Test the property 'AuthAthenzParams'
        /// </summary>
        [Fact]
        public void AuthAthenzParamsTest()
        {
            // TODO unit test for the property 'AuthAthenzParams'
        }

        /// <summary>
        /// Test the property 'AuthAthenzSecret'
        /// </summary>
        [Fact]
        public void AuthAthenzSecretTest()
        {
            // TODO unit test for the property 'AuthAthenzSecret'
        }

        /// <summary>
        /// Test the property 'AuthTokenSecret'
        /// </summary>
        [Fact]
        public void AuthTokenSecretTest()
        {
            // TODO unit test for the property 'AuthTokenSecret'
        }

        /// <summary>
        /// Test the property 'ConnectionBackoff'
        /// </summary>
        [Fact]
        public void ConnectionBackoffTest()
        {
            // TODO unit test for the property 'ConnectionBackoff'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'JsonBody'
        /// </summary>
        [Fact]
        public void JsonBodyTest()
        {
            // TODO unit test for the property 'JsonBody'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Tls'
        /// </summary>
        [Fact]
        public void TlsTest()
        {
            // TODO unit test for the property 'Tls'
        }

        /// <summary>
        /// Test the property 'TlsAllowInsecureConnection'
        /// </summary>
        [Fact]
        public void TlsAllowInsecureConnectionTest()
        {
            // TODO unit test for the property 'TlsAllowInsecureConnection'
        }

        /// <summary>
        /// Test the property 'TlsTrustCertsSecret'
        /// </summary>
        [Fact]
        public void TlsTrustCertsSecretTest()
        {
            // TODO unit test for the property 'TlsTrustCertsSecret'
        }

        /// <summary>
        /// Test the property 'TlsValidateHostname'
        /// </summary>
        [Fact]
        public void TlsValidateHostnameTest()
        {
            // TODO unit test for the property 'TlsValidateHostname'
        }

        /// <summary>
        /// Test the property 'Topics'
        /// </summary>
        [Fact]
        public void TopicsTest()
        {
            // TODO unit test for the property 'Topics'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
