/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojEventsV1alpha1AzureEventsHubEventSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojEventsV1alpha1AzureEventsHubEventSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojEventsV1alpha1AzureEventsHubEventSource
        //private IoArgoprojEventsV1alpha1AzureEventsHubEventSource instance;

        public IoArgoprojEventsV1alpha1AzureEventsHubEventSourceTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojEventsV1alpha1AzureEventsHubEventSource
            //instance = new IoArgoprojEventsV1alpha1AzureEventsHubEventSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojEventsV1alpha1AzureEventsHubEventSource
        /// </summary>
        [Fact]
        public void IoArgoprojEventsV1alpha1AzureEventsHubEventSourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojEventsV1alpha1AzureEventsHubEventSource
            //Assert.IsType<IoArgoprojEventsV1alpha1AzureEventsHubEventSource>(instance);
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'Fqdn'
        /// </summary>
        [Fact]
        public void FqdnTest()
        {
            // TODO unit test for the property 'Fqdn'
        }

        /// <summary>
        /// Test the property 'HubName'
        /// </summary>
        [Fact]
        public void HubNameTest()
        {
            // TODO unit test for the property 'HubName'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'SharedAccessKey'
        /// </summary>
        [Fact]
        public void SharedAccessKeyTest()
        {
            // TODO unit test for the property 'SharedAccessKey'
        }

        /// <summary>
        /// Test the property 'SharedAccessKeyName'
        /// </summary>
        [Fact]
        public void SharedAccessKeyNameTest()
        {
            // TODO unit test for the property 'SharedAccessKeyName'
        }
    }
}
