/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoArgoprojEventsV1alpha1ResourceEventSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoArgoprojEventsV1alpha1ResourceEventSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoArgoprojEventsV1alpha1ResourceEventSource
        //private IoArgoprojEventsV1alpha1ResourceEventSource instance;

        public IoArgoprojEventsV1alpha1ResourceEventSourceTests()
        {
            // TODO uncomment below to create an instance of IoArgoprojEventsV1alpha1ResourceEventSource
            //instance = new IoArgoprojEventsV1alpha1ResourceEventSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoArgoprojEventsV1alpha1ResourceEventSource
        /// </summary>
        [Fact]
        public void IoArgoprojEventsV1alpha1ResourceEventSourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoArgoprojEventsV1alpha1ResourceEventSource
            //Assert.IsType<IoArgoprojEventsV1alpha1ResourceEventSource>(instance);
        }

        /// <summary>
        /// Test the property 'EventTypes'
        /// </summary>
        [Fact]
        public void EventTypesTest()
        {
            // TODO unit test for the property 'EventTypes'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'GroupVersionResource'
        /// </summary>
        [Fact]
        public void GroupVersionResourceTest()
        {
            // TODO unit test for the property 'GroupVersionResource'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
    }
}
