/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoK8sApimachineryPkgApisMetaV1GroupVersionResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoK8sApimachineryPkgApisMetaV1GroupVersionResourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoK8sApimachineryPkgApisMetaV1GroupVersionResource
        //private IoK8sApimachineryPkgApisMetaV1GroupVersionResource instance;

        public IoK8sApimachineryPkgApisMetaV1GroupVersionResourceTests()
        {
            // TODO uncomment below to create an instance of IoK8sApimachineryPkgApisMetaV1GroupVersionResource
            //instance = new IoK8sApimachineryPkgApisMetaV1GroupVersionResource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoK8sApimachineryPkgApisMetaV1GroupVersionResource
        /// </summary>
        [Fact]
        public void IoK8sApimachineryPkgApisMetaV1GroupVersionResourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoK8sApimachineryPkgApisMetaV1GroupVersionResource
            //Assert.IsType<IoK8sApimachineryPkgApisMetaV1GroupVersionResource>(instance);
        }

        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Fact]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
