/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoK8sApiCoreV1TCPSocketAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoK8sApiCoreV1TCPSocketActionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoK8sApiCoreV1TCPSocketAction
        //private IoK8sApiCoreV1TCPSocketAction instance;

        public IoK8sApiCoreV1TCPSocketActionTests()
        {
            // TODO uncomment below to create an instance of IoK8sApiCoreV1TCPSocketAction
            //instance = new IoK8sApiCoreV1TCPSocketAction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoK8sApiCoreV1TCPSocketAction
        /// </summary>
        [Fact]
        public void IoK8sApiCoreV1TCPSocketActionInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoK8sApiCoreV1TCPSocketAction
            //Assert.IsType<IoK8sApiCoreV1TCPSocketAction>(instance);
        }

        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Fact]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }

        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Fact]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
    }
}
