/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoK8sApiCoreV1Event
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoK8sApiCoreV1EventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoK8sApiCoreV1Event
        //private IoK8sApiCoreV1Event instance;

        public IoK8sApiCoreV1EventTests()
        {
            // TODO uncomment below to create an instance of IoK8sApiCoreV1Event
            //instance = new IoK8sApiCoreV1Event();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoK8sApiCoreV1Event
        /// </summary>
        [Fact]
        public void IoK8sApiCoreV1EventInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoK8sApiCoreV1Event
            //Assert.IsType<IoK8sApiCoreV1Event>(instance);
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'ApiVersion'
        /// </summary>
        [Fact]
        public void ApiVersionTest()
        {
            // TODO unit test for the property 'ApiVersion'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'EventTime'
        /// </summary>
        [Fact]
        public void EventTimeTest()
        {
            // TODO unit test for the property 'EventTime'
        }

        /// <summary>
        /// Test the property 'FirstTimestamp'
        /// </summary>
        [Fact]
        public void FirstTimestampTest()
        {
            // TODO unit test for the property 'FirstTimestamp'
        }

        /// <summary>
        /// Test the property 'InvolvedObject'
        /// </summary>
        [Fact]
        public void InvolvedObjectTest()
        {
            // TODO unit test for the property 'InvolvedObject'
        }

        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Fact]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }

        /// <summary>
        /// Test the property 'LastTimestamp'
        /// </summary>
        [Fact]
        public void LastTimestampTest()
        {
            // TODO unit test for the property 'LastTimestamp'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'Related'
        /// </summary>
        [Fact]
        public void RelatedTest()
        {
            // TODO unit test for the property 'Related'
        }

        /// <summary>
        /// Test the property 'ReportingComponent'
        /// </summary>
        [Fact]
        public void ReportingComponentTest()
        {
            // TODO unit test for the property 'ReportingComponent'
        }

        /// <summary>
        /// Test the property 'ReportingInstance'
        /// </summary>
        [Fact]
        public void ReportingInstanceTest()
        {
            // TODO unit test for the property 'ReportingInstance'
        }

        /// <summary>
        /// Test the property 'Series'
        /// </summary>
        [Fact]
        public void SeriesTest()
        {
            // TODO unit test for the property 'Series'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
