/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoK8sApiPolicyV1PodDisruptionBudgetSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoK8sApiPolicyV1PodDisruptionBudgetSpecTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoK8sApiPolicyV1PodDisruptionBudgetSpec
        //private IoK8sApiPolicyV1PodDisruptionBudgetSpec instance;

        public IoK8sApiPolicyV1PodDisruptionBudgetSpecTests()
        {
            // TODO uncomment below to create an instance of IoK8sApiPolicyV1PodDisruptionBudgetSpec
            //instance = new IoK8sApiPolicyV1PodDisruptionBudgetSpec();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoK8sApiPolicyV1PodDisruptionBudgetSpec
        /// </summary>
        [Fact]
        public void IoK8sApiPolicyV1PodDisruptionBudgetSpecInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoK8sApiPolicyV1PodDisruptionBudgetSpec
            //Assert.IsType<IoK8sApiPolicyV1PodDisruptionBudgetSpec>(instance);
        }

        /// <summary>
        /// Test the property 'MaxUnavailable'
        /// </summary>
        [Fact]
        public void MaxUnavailableTest()
        {
            // TODO unit test for the property 'MaxUnavailable'
        }

        /// <summary>
        /// Test the property 'MinAvailable'
        /// </summary>
        [Fact]
        public void MinAvailableTest()
        {
            // TODO unit test for the property 'MinAvailable'
        }

        /// <summary>
        /// Test the property 'Selector'
        /// </summary>
        [Fact]
        public void SelectorTest()
        {
            // TODO unit test for the property 'Selector'
        }
    }
}
