/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirementTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement
        //private IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement instance;

        public IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirementTests()
        {
            // TODO uncomment below to create an instance of IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement
            //instance = new IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement
        /// </summary>
        [Fact]
        public void IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirementInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement
            //Assert.IsType<IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Fact]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }

        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
    }
}
