/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IoK8sApiCoreV1PersistentVolumeClaimCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IoK8sApiCoreV1PersistentVolumeClaimConditionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IoK8sApiCoreV1PersistentVolumeClaimCondition
        //private IoK8sApiCoreV1PersistentVolumeClaimCondition instance;

        public IoK8sApiCoreV1PersistentVolumeClaimConditionTests()
        {
            // TODO uncomment below to create an instance of IoK8sApiCoreV1PersistentVolumeClaimCondition
            //instance = new IoK8sApiCoreV1PersistentVolumeClaimCondition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IoK8sApiCoreV1PersistentVolumeClaimCondition
        /// </summary>
        [Fact]
        public void IoK8sApiCoreV1PersistentVolumeClaimConditionInstanceTest()
        {
            // TODO uncomment below to test "IsType" IoK8sApiCoreV1PersistentVolumeClaimCondition
            //Assert.IsType<IoK8sApiCoreV1PersistentVolumeClaimCondition>(instance);
        }

        /// <summary>
        /// Test the property 'LastProbeTime'
        /// </summary>
        [Fact]
        public void LastProbeTimeTest()
        {
            // TODO unit test for the property 'LastProbeTime'
        }

        /// <summary>
        /// Test the property 'LastTransitionTime'
        /// </summary>
        [Fact]
        public void LastTransitionTimeTest()
        {
            // TODO unit test for the property 'LastTransitionTime'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
