/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SensorUpdateSensorRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SensorUpdateSensorRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SensorUpdateSensorRequest
        //private SensorUpdateSensorRequest instance;

        public SensorUpdateSensorRequestTests()
        {
            // TODO uncomment below to create an instance of SensorUpdateSensorRequest
            //instance = new SensorUpdateSensorRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SensorUpdateSensorRequest
        /// </summary>
        [Fact]
        public void SensorUpdateSensorRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SensorUpdateSensorRequest
            //Assert.IsType<SensorUpdateSensorRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }

        /// <summary>
        /// Test the property 'Sensor'
        /// </summary>
        [Fact]
        public void SensorTest()
        {
            // TODO unit test for the property 'Sensor'
        }
    }
}
